// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge_message.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_judge_5fmessage_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_judge_5fmessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_judge_5fmessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_judge_5fmessage_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_judge_5fmessage_2eproto;
namespace judge_message_for_transport {
class recTestInfo;
struct recTestInfoDefaultTypeInternal;
extern recTestInfoDefaultTypeInternal _recTestInfo_default_instance_;
class testPointResult;
struct testPointResultDefaultTypeInternal;
extern testPointResultDefaultTypeInternal _testPointResult_default_instance_;
class testResult;
struct testResultDefaultTypeInternal;
extern testResultDefaultTypeInternal _testResult_default_instance_;
}  // namespace judge_message_for_transport
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace judge_message_for_transport {
enum testResult_errType : int {
  testResult_errType_COMPILE_ERR = 0,
  testResult_errType_NOT_HAVE_PROBLEM = 1,
  testResult_errType_NOT_HAVE_DATA = 2,
  testResult_errType_OTHER = 3,
};

bool testResult_errType_IsValid(int value);
extern const uint32_t testResult_errType_internal_data_[];
constexpr testResult_errType testResult_errType_errType_MIN = static_cast<testResult_errType>(0);
constexpr testResult_errType testResult_errType_errType_MAX = static_cast<testResult_errType>(3);
constexpr int testResult_errType_errType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
testResult_errType_descriptor();
template <typename T>
const std::string& testResult_errType_Name(T value) {
  static_assert(std::is_same<T, testResult_errType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to errType_Name().");
  return testResult_errType_Name(static_cast<testResult_errType>(value));
}
template <>
inline const std::string& testResult_errType_Name(testResult_errType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<testResult_errType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool testResult_errType_Parse(absl::string_view name, testResult_errType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<testResult_errType>(
      testResult_errType_descriptor(), name, value);
}
enum recTestInfo_language : int {
  recTestInfo_language_cpp = 0,
  recTestInfo_language_c = 1,
  recTestInfo_language_python = 2,
};

bool recTestInfo_language_IsValid(int value);
extern const uint32_t recTestInfo_language_internal_data_[];
constexpr recTestInfo_language recTestInfo_language_language_MIN = static_cast<recTestInfo_language>(0);
constexpr recTestInfo_language recTestInfo_language_language_MAX = static_cast<recTestInfo_language>(2);
constexpr int recTestInfo_language_language_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
recTestInfo_language_descriptor();
template <typename T>
const std::string& recTestInfo_language_Name(T value) {
  static_assert(std::is_same<T, recTestInfo_language>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to language_Name().");
  return recTestInfo_language_Name(static_cast<recTestInfo_language>(value));
}
template <>
inline const std::string& recTestInfo_language_Name(recTestInfo_language value) {
  return ::google::protobuf::internal::NameOfDenseEnum<recTestInfo_language_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool recTestInfo_language_Parse(absl::string_view name, recTestInfo_language* value) {
  return ::google::protobuf::internal::ParseNamedEnum<recTestInfo_language>(
      recTestInfo_language_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class testPointResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:judge_message_for_transport.testPointResult) */ {
 public:
  inline testPointResult() : testPointResult(nullptr) {}
  ~testPointResult() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR testPointResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline testPointResult(const testPointResult& from) : testPointResult(nullptr, from) {}
  inline testPointResult(testPointResult&& from) noexcept
      : testPointResult(nullptr, std::move(from)) {}
  inline testPointResult& operator=(const testPointResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline testPointResult& operator=(testPointResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const testPointResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const testPointResult* internal_default_instance() {
    return reinterpret_cast<const testPointResult*>(
        &_testPointResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(testPointResult& a, testPointResult& b) { a.Swap(&b); }
  inline void Swap(testPointResult* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(testPointResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  testPointResult* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<testPointResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const testPointResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const testPointResult& from) { testPointResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(testPointResult* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "judge_message_for_transport.testPointResult"; }

 protected:
  explicit testPointResult(::google::protobuf::Arena* arena);
  testPointResult(::google::protobuf::Arena* arena, const testPointResult& from);
  testPointResult(::google::protobuf::Arena* arena, testPointResult&& from) noexcept
      : testPointResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 9,
    kSeqIdFieldNumber = 1,
    kCpuTimeFieldNumber = 2,
    kMemoryFieldNumber = 4,
    kRealTimeFieldNumber = 3,
    kSignalFieldNumber = 5,
    kExitCodeFieldNumber = 6,
    kErrorFieldNumber = 7,
    kResultFieldNumber = 8,
  };
  // optional string msg = 9;
  bool has_msg() const;
  void clear_msg() ;
  const std::string& msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* value);

  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(
      const std::string& value);
  std::string* _internal_mutable_msg();

  public:
  // required int32 seq_id = 1;
  bool has_seq_id() const;
  void clear_seq_id() ;
  ::int32_t seq_id() const;
  void set_seq_id(::int32_t value);

  private:
  ::int32_t _internal_seq_id() const;
  void _internal_set_seq_id(::int32_t value);

  public:
  // required int32 cpu_time = 2;
  bool has_cpu_time() const;
  void clear_cpu_time() ;
  ::int32_t cpu_time() const;
  void set_cpu_time(::int32_t value);

  private:
  ::int32_t _internal_cpu_time() const;
  void _internal_set_cpu_time(::int32_t value);

  public:
  // required int64 memory = 4;
  bool has_memory() const;
  void clear_memory() ;
  ::int64_t memory() const;
  void set_memory(::int64_t value);

  private:
  ::int64_t _internal_memory() const;
  void _internal_set_memory(::int64_t value);

  public:
  // required int32 real_time = 3;
  bool has_real_time() const;
  void clear_real_time() ;
  ::int32_t real_time() const;
  void set_real_time(::int32_t value);

  private:
  ::int32_t _internal_real_time() const;
  void _internal_set_real_time(::int32_t value);

  public:
  // required int32 signal = 5;
  bool has_signal() const;
  void clear_signal() ;
  ::int32_t signal() const;
  void set_signal(::int32_t value);

  private:
  ::int32_t _internal_signal() const;
  void _internal_set_signal(::int32_t value);

  public:
  // required int32 exit_code = 6;
  bool has_exit_code() const;
  void clear_exit_code() ;
  ::int32_t exit_code() const;
  void set_exit_code(::int32_t value);

  private:
  ::int32_t _internal_exit_code() const;
  void _internal_set_exit_code(::int32_t value);

  public:
  // required int32 error = 7;
  bool has_error() const;
  void clear_error() ;
  ::int32_t error() const;
  void set_error(::int32_t value);

  private:
  ::int32_t _internal_error() const;
  void _internal_set_error(::int32_t value);

  public:
  // required int32 result = 8;
  bool has_result() const;
  void clear_result() ;
  ::int32_t result() const;
  void set_result(::int32_t value);

  private:
  ::int32_t _internal_result() const;
  void _internal_set_result(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:judge_message_for_transport.testPointResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      63, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_testPointResult_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const testPointResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::int32_t seq_id_;
    ::int32_t cpu_time_;
    ::int64_t memory_;
    ::int32_t real_time_;
    ::int32_t signal_;
    ::int32_t exit_code_;
    ::int32_t error_;
    ::int32_t result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class recTestInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:judge_message_for_transport.recTestInfo) */ {
 public:
  inline recTestInfo() : recTestInfo(nullptr) {}
  ~recTestInfo() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR recTestInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline recTestInfo(const recTestInfo& from) : recTestInfo(nullptr, from) {}
  inline recTestInfo(recTestInfo&& from) noexcept
      : recTestInfo(nullptr, std::move(from)) {}
  inline recTestInfo& operator=(const recTestInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline recTestInfo& operator=(recTestInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const recTestInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const recTestInfo* internal_default_instance() {
    return reinterpret_cast<const recTestInfo*>(
        &_recTestInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(recTestInfo& a, recTestInfo& b) { a.Swap(&b); }
  inline void Swap(recTestInfo* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(recTestInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  recTestInfo* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<recTestInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const recTestInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const recTestInfo& from) { recTestInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(recTestInfo* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "judge_message_for_transport.recTestInfo"; }

 protected:
  explicit recTestInfo(::google::protobuf::Arena* arena);
  recTestInfo(::google::protobuf::Arena* arena, const recTestInfo& from);
  recTestInfo(::google::protobuf::Arena* arena, recTestInfo&& from) noexcept
      : recTestInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using language = recTestInfo_language;
  static constexpr language cpp = recTestInfo_language_cpp;
  static constexpr language c = recTestInfo_language_c;
  static constexpr language python = recTestInfo_language_python;
  static inline bool language_IsValid(int value) {
    return recTestInfo_language_IsValid(value);
  }
  static constexpr language language_MIN = recTestInfo_language_language_MIN;
  static constexpr language language_MAX = recTestInfo_language_language_MAX;
  static constexpr int language_ARRAYSIZE = recTestInfo_language_language_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* language_descriptor() {
    return recTestInfo_language_descriptor();
  }
  template <typename T>
  static inline const std::string& language_Name(T value) {
    return recTestInfo_language_Name(value);
  }
  static inline bool language_Parse(absl::string_view name, language* value) {
    return recTestInfo_language_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPidFieldNumber = 2,
    kCodeFieldNumber = 3,
    kUuidFieldNumber = 1,
  };
  // required string pid = 2;
  bool has_pid() const;
  void clear_pid() ;
  const std::string& pid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pid(Arg_&& arg, Args_... args);
  std::string* mutable_pid();
  PROTOBUF_NODISCARD std::string* release_pid();
  void set_allocated_pid(std::string* value);

  private:
  const std::string& _internal_pid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pid(
      const std::string& value);
  std::string* _internal_mutable_pid();

  public:
  // required string code = 3;
  bool has_code() const;
  void clear_code() ;
  const std::string& code() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_code(Arg_&& arg, Args_... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* value);

  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(
      const std::string& value);
  std::string* _internal_mutable_code();

  public:
  // required int32 uuid = 1;
  bool has_uuid() const;
  void clear_uuid() ;
  ::int32_t uuid() const;
  void set_uuid(::int32_t value);

  private:
  ::int32_t _internal_uuid() const;
  void _internal_set_uuid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:judge_message_for_transport.recTestInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      55, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_recTestInfo_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const recTestInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pid_;
    ::google::protobuf::internal::ArenaStringPtr code_;
    ::int32_t uuid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class testResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:judge_message_for_transport.testResult) */ {
 public:
  inline testResult() : testResult(nullptr) {}
  ~testResult() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR testResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline testResult(const testResult& from) : testResult(nullptr, from) {}
  inline testResult(testResult&& from) noexcept
      : testResult(nullptr, std::move(from)) {}
  inline testResult& operator=(const testResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline testResult& operator=(testResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const testResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const testResult* internal_default_instance() {
    return reinterpret_cast<const testResult*>(
        &_testResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(testResult& a, testResult& b) { a.Swap(&b); }
  inline void Swap(testResult* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(testResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  testResult* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<testResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const testResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const testResult& from) { testResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(testResult* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "judge_message_for_transport.testResult"; }

 protected:
  explicit testResult(::google::protobuf::Arena* arena);
  testResult(::google::protobuf::Arena* arena, const testResult& from);
  testResult(::google::protobuf::Arena* arena, testResult&& from) noexcept
      : testResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using errType = testResult_errType;
  static constexpr errType COMPILE_ERR = testResult_errType_COMPILE_ERR;
  static constexpr errType NOT_HAVE_PROBLEM = testResult_errType_NOT_HAVE_PROBLEM;
  static constexpr errType NOT_HAVE_DATA = testResult_errType_NOT_HAVE_DATA;
  static constexpr errType OTHER = testResult_errType_OTHER;
  static inline bool errType_IsValid(int value) {
    return testResult_errType_IsValid(value);
  }
  static constexpr errType errType_MIN = testResult_errType_errType_MIN;
  static constexpr errType errType_MAX = testResult_errType_errType_MAX;
  static constexpr int errType_ARRAYSIZE = testResult_errType_errType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* errType_descriptor() {
    return testResult_errType_descriptor();
  }
  template <typename T>
  static inline const std::string& errType_Name(T value) {
    return testResult_errType_Name(value);
  }
  static inline bool errType_Parse(absl::string_view name, errType* value) {
    return testResult_errType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kResultsFieldNumber = 3,
    kUuidFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // repeated .judge_message_for_transport.testPointResult results = 3;
  int results_size() const;
  private:
  int _internal_results_size() const;

  public:
  void clear_results() ;
  ::judge_message_for_transport::testPointResult* mutable_results(int index);
  ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>* mutable_results();

  private:
  const ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>& _internal_results() const;
  ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>* _internal_mutable_results();
  public:
  const ::judge_message_for_transport::testPointResult& results(int index) const;
  ::judge_message_for_transport::testPointResult* add_results();
  const ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>& results() const;
  // required int32 uuid = 1;
  bool has_uuid() const;
  void clear_uuid() ;
  ::int32_t uuid() const;
  void set_uuid(::int32_t value);

  private:
  ::int32_t _internal_uuid() const;
  void _internal_set_uuid(::int32_t value);

  public:
  // optional .judge_message_for_transport.testResult.errType type = 2;
  bool has_type() const;
  void clear_type() ;
  ::judge_message_for_transport::testResult_errType type() const;
  void set_type(::judge_message_for_transport::testResult_errType value);

  private:
  ::judge_message_for_transport::testResult_errType _internal_type() const;
  void _internal_set_type(::judge_message_for_transport::testResult_errType value);

  public:
  // @@protoc_insertion_point(class_scope:judge_message_for_transport.testResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_testResult_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const testResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::judge_message_for_transport::testPointResult > results_;
    ::int32_t uuid_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fmessage_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// testPointResult

// required int32 seq_id = 1;
inline bool testPointResult::has_seq_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void testPointResult::clear_seq_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t testPointResult::seq_id() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.seq_id)
  return _internal_seq_id();
}
inline void testPointResult::set_seq_id(::int32_t value) {
  _internal_set_seq_id(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.seq_id)
}
inline ::int32_t testPointResult::_internal_seq_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seq_id_;
}
inline void testPointResult::_internal_set_seq_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_id_ = value;
}

// required int32 cpu_time = 2;
inline bool testPointResult::has_cpu_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void testPointResult::clear_cpu_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_time_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t testPointResult::cpu_time() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.cpu_time)
  return _internal_cpu_time();
}
inline void testPointResult::set_cpu_time(::int32_t value) {
  _internal_set_cpu_time(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.cpu_time)
}
inline ::int32_t testPointResult::_internal_cpu_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_time_;
}
inline void testPointResult::_internal_set_cpu_time(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_time_ = value;
}

// required int32 real_time = 3;
inline bool testPointResult::has_real_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void testPointResult::clear_real_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_time_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t testPointResult::real_time() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.real_time)
  return _internal_real_time();
}
inline void testPointResult::set_real_time(::int32_t value) {
  _internal_set_real_time(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.real_time)
}
inline ::int32_t testPointResult::_internal_real_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.real_time_;
}
inline void testPointResult::_internal_set_real_time(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.real_time_ = value;
}

// required int64 memory = 4;
inline bool testPointResult::has_memory() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void testPointResult::clear_memory() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int64_t testPointResult::memory() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.memory)
  return _internal_memory();
}
inline void testPointResult::set_memory(::int64_t value) {
  _internal_set_memory(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.memory)
}
inline ::int64_t testPointResult::_internal_memory() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.memory_;
}
inline void testPointResult::_internal_set_memory(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.memory_ = value;
}

// required int32 signal = 5;
inline bool testPointResult::has_signal() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void testPointResult::clear_signal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t testPointResult::signal() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.signal)
  return _internal_signal();
}
inline void testPointResult::set_signal(::int32_t value) {
  _internal_set_signal(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.signal)
}
inline ::int32_t testPointResult::_internal_signal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signal_;
}
inline void testPointResult::_internal_set_signal(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_ = value;
}

// required int32 exit_code = 6;
inline bool testPointResult::has_exit_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void testPointResult::clear_exit_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exit_code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t testPointResult::exit_code() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.exit_code)
  return _internal_exit_code();
}
inline void testPointResult::set_exit_code(::int32_t value) {
  _internal_set_exit_code(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.exit_code)
}
inline ::int32_t testPointResult::_internal_exit_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exit_code_;
}
inline void testPointResult::_internal_set_exit_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exit_code_ = value;
}

// required int32 error = 7;
inline bool testPointResult::has_error() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void testPointResult::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t testPointResult::error() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.error)
  return _internal_error();
}
inline void testPointResult::set_error(::int32_t value) {
  _internal_set_error(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.error)
}
inline ::int32_t testPointResult::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_;
}
inline void testPointResult::_internal_set_error(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// required int32 result = 8;
inline bool testPointResult::has_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void testPointResult::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t testPointResult::result() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.result)
  return _internal_result();
}
inline void testPointResult::set_result(::int32_t value) {
  _internal_set_result(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.result)
}
inline ::int32_t testPointResult::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void testPointResult::_internal_set_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// optional string msg = 9;
inline bool testPointResult::has_msg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void testPointResult::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& testPointResult::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testPointResult.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void testPointResult::set_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testPointResult.msg)
}
inline std::string* testPointResult::mutable_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:judge_message_for_transport.testPointResult.msg)
  return _s;
}
inline const std::string& testPointResult::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void testPointResult::_internal_set_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_.Set(value, GetArena());
}
inline std::string* testPointResult::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.msg_.Mutable( GetArena());
}
inline std::string* testPointResult::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:judge_message_for_transport.testPointResult.msg)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.msg_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.msg_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void testPointResult::set_allocated_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.msg_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.msg_.IsDefault()) {
          _impl_.msg_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:judge_message_for_transport.testPointResult.msg)
}

// -------------------------------------------------------------------

// testResult

// required int32 uuid = 1;
inline bool testResult::has_uuid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void testResult::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t testResult::uuid() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testResult.uuid)
  return _internal_uuid();
}
inline void testResult::set_uuid(::int32_t value) {
  _internal_set_uuid(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testResult.uuid)
}
inline ::int32_t testResult::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_;
}
inline void testResult::_internal_set_uuid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_ = value;
}

// optional .judge_message_for_transport.testResult.errType type = 2;
inline bool testResult::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void testResult::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::judge_message_for_transport::testResult_errType testResult::type() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testResult.type)
  return _internal_type();
}
inline void testResult::set_type(::judge_message_for_transport::testResult_errType value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.testResult.type)
}
inline ::judge_message_for_transport::testResult_errType testResult::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::judge_message_for_transport::testResult_errType>(_impl_.type_);
}
inline void testResult::_internal_set_type(::judge_message_for_transport::testResult_errType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::judge_message_for_transport::testResult_errType_IsValid(value));
  _impl_.type_ = value;
}

// repeated .judge_message_for_transport.testPointResult results = 3;
inline int testResult::_internal_results_size() const {
  return _internal_results().size();
}
inline int testResult::results_size() const {
  return _internal_results_size();
}
inline void testResult::clear_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.results_.Clear();
}
inline ::judge_message_for_transport::testPointResult* testResult::mutable_results(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:judge_message_for_transport.testResult.results)
  return _internal_mutable_results()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>* testResult::mutable_results()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:judge_message_for_transport.testResult.results)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_results();
}
inline const ::judge_message_for_transport::testPointResult& testResult::results(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.testResult.results)
  return _internal_results().Get(index);
}
inline ::judge_message_for_transport::testPointResult* testResult::add_results() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::judge_message_for_transport::testPointResult* _add = _internal_mutable_results()->Add();
  // @@protoc_insertion_point(field_add:judge_message_for_transport.testResult.results)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>& testResult::results() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:judge_message_for_transport.testResult.results)
  return _internal_results();
}
inline const ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>&
testResult::_internal_results() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.results_;
}
inline ::google::protobuf::RepeatedPtrField<::judge_message_for_transport::testPointResult>*
testResult::_internal_mutable_results() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.results_;
}

// -------------------------------------------------------------------

// recTestInfo

// required int32 uuid = 1;
inline bool recTestInfo::has_uuid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void recTestInfo::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t recTestInfo::uuid() const {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.recTestInfo.uuid)
  return _internal_uuid();
}
inline void recTestInfo::set_uuid(::int32_t value) {
  _internal_set_uuid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:judge_message_for_transport.recTestInfo.uuid)
}
inline ::int32_t recTestInfo::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_;
}
inline void recTestInfo::_internal_set_uuid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_ = value;
}

// required string pid = 2;
inline bool recTestInfo::has_pid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void recTestInfo::clear_pid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& recTestInfo::pid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.recTestInfo.pid)
  return _internal_pid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void recTestInfo::set_pid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:judge_message_for_transport.recTestInfo.pid)
}
inline std::string* recTestInfo::mutable_pid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pid();
  // @@protoc_insertion_point(field_mutable:judge_message_for_transport.recTestInfo.pid)
  return _s;
}
inline const std::string& recTestInfo::_internal_pid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pid_.Get();
}
inline void recTestInfo::_internal_set_pid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pid_.Set(value, GetArena());
}
inline std::string* recTestInfo::_internal_mutable_pid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pid_.Mutable( GetArena());
}
inline std::string* recTestInfo::release_pid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:judge_message_for_transport.recTestInfo.pid)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void recTestInfo::set_allocated_pid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pid_.IsDefault()) {
          _impl_.pid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:judge_message_for_transport.recTestInfo.pid)
}

// required string code = 3;
inline bool recTestInfo::has_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void recTestInfo::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& recTestInfo::code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:judge_message_for_transport.recTestInfo.code)
  return _internal_code();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void recTestInfo::set_code(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.code_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:judge_message_for_transport.recTestInfo.code)
}
inline std::string* recTestInfo::mutable_code() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:judge_message_for_transport.recTestInfo.code)
  return _s;
}
inline const std::string& recTestInfo::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_.Get();
}
inline void recTestInfo::_internal_set_code(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.code_.Set(value, GetArena());
}
inline std::string* recTestInfo::_internal_mutable_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.code_.Mutable( GetArena());
}
inline std::string* recTestInfo::release_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:judge_message_for_transport.recTestInfo.code)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.code_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.code_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void recTestInfo::set_allocated_code(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.code_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.code_.IsDefault()) {
          _impl_.code_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:judge_message_for_transport.recTestInfo.code)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace judge_message_for_transport


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::judge_message_for_transport::testResult_errType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::judge_message_for_transport::testResult_errType>() {
  return ::judge_message_for_transport::testResult_errType_descriptor();
}
template <>
struct is_proto_enum<::judge_message_for_transport::recTestInfo_language> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::judge_message_for_transport::recTestInfo_language>() {
  return ::judge_message_for_transport::recTestInfo_language_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_judge_5fmessage_2eproto_2epb_2eh
