// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge_message.proto
// Protobuf C++ Version: 5.28.2

#include "judge_message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace judge_message_for_transport {

inline constexpr testPointResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        seq_id_{0},
        cpu_time_{0},
        memory_{::int64_t{0}},
        real_time_{0},
        signal_{0},
        exit_code_{0},
        error_{0},
        result_{0} {}

template <typename>
PROTOBUF_CONSTEXPR testPointResult::testPointResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct testPointResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR testPointResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~testPointResultDefaultTypeInternal() {}
  union {
    testPointResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 testPointResultDefaultTypeInternal _testPointResult_default_instance_;

inline constexpr recTestInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uuid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR recTestInfo::recTestInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct recTestInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR recTestInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~recTestInfoDefaultTypeInternal() {}
  union {
    recTestInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 recTestInfoDefaultTypeInternal _recTestInfo_default_instance_;

inline constexpr testResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        results_{},
        uuid_{0},
        type_{static_cast< ::judge_message_for_transport::testResult_errType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR testResult::testResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct testResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR testResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~testResultDefaultTypeInternal() {}
  union {
    testResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 testResultDefaultTypeInternal _testResult_default_instance_;
}  // namespace judge_message_for_transport
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_judge_5fmessage_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_judge_5fmessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_judge_5fmessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.seq_id_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.cpu_time_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.real_time_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.memory_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.signal_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.exit_code_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testPointResult, _impl_.msg_),
        1,
        2,
        4,
        3,
        5,
        6,
        7,
        8,
        0,
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testResult, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testResult, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::testResult, _impl_.results_),
        0,
        1,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::recTestInfo, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::recTestInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::recTestInfo, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::recTestInfo, _impl_.pid_),
        PROTOBUF_FIELD_OFFSET(::judge_message_for_transport::recTestInfo, _impl_.code_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 17, -1, sizeof(::judge_message_for_transport::testPointResult)},
        {26, 37, -1, sizeof(::judge_message_for_transport::testResult)},
        {40, 51, -1, sizeof(::judge_message_for_transport::recTestInfo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::judge_message_for_transport::_testPointResult_default_instance_._instance,
    &::judge_message_for_transport::_testResult_default_instance_._instance,
    &::judge_message_for_transport::_recTestInfo_default_instance_._instance,
};
const char descriptor_table_protodef_judge_5fmessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023judge_message.proto\022\033judge_message_for"
    "_transport\"\245\001\n\017testPointResult\022\016\n\006seq_id"
    "\030\001 \002(\005\022\020\n\010cpu_time\030\002 \002(\005\022\021\n\treal_time\030\003 "
    "\002(\005\022\016\n\006memory\030\004 \002(\003\022\016\n\006signal\030\005 \002(\005\022\021\n\te"
    "xit_code\030\006 \002(\005\022\r\n\005error\030\007 \002(\005\022\016\n\006result\030"
    "\010 \002(\005\022\013\n\003msg\030\t \001(\t\"\350\001\n\ntestResult\022\014\n\004uui"
    "d\030\001 \002(\005\022=\n\004type\030\002 \001(\0162/.judge_message_fo"
    "r_transport.testResult.errType\022=\n\007result"
    "s\030\003 \003(\0132,.judge_message_for_transport.te"
    "stPointResult\"N\n\007errType\022\017\n\013COMPILE_ERR\020"
    "\000\022\024\n\020NOT_HAVE_PROBLEM\020\001\022\021\n\rNOT_HAVE_DATA"
    "\020\002\022\t\n\005OTHER\020\003\"^\n\013recTestInfo\022\014\n\004uuid\030\001 \002"
    "(\005\022\013\n\003pid\030\002 \002(\t\022\014\n\004code\030\003 \002(\t\"&\n\010languag"
    "e\022\007\n\003cpp\020\000\022\005\n\001c\020\001\022\n\n\006python\020\002"
};
static ::absl::once_flag descriptor_table_judge_5fmessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_judge_5fmessage_2eproto = {
    false,
    false,
    549,
    descriptor_table_protodef_judge_5fmessage_2eproto,
    "judge_message.proto",
    &descriptor_table_judge_5fmessage_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_judge_5fmessage_2eproto::offsets,
    file_level_enum_descriptors_judge_5fmessage_2eproto,
    file_level_service_descriptors_judge_5fmessage_2eproto,
};
namespace judge_message_for_transport {
const ::google::protobuf::EnumDescriptor* testResult_errType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_judge_5fmessage_2eproto);
  return file_level_enum_descriptors_judge_5fmessage_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t testResult_errType_internal_data_[] = {
    262144u, 0u, };
bool testResult_errType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr testResult_errType testResult::COMPILE_ERR;
constexpr testResult_errType testResult::NOT_HAVE_PROBLEM;
constexpr testResult_errType testResult::NOT_HAVE_DATA;
constexpr testResult_errType testResult::OTHER;
constexpr testResult_errType testResult::errType_MIN;
constexpr testResult_errType testResult::errType_MAX;
constexpr int testResult::errType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* recTestInfo_language_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_judge_5fmessage_2eproto);
  return file_level_enum_descriptors_judge_5fmessage_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t recTestInfo_language_internal_data_[] = {
    196608u, 0u, };
bool recTestInfo_language_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr recTestInfo_language recTestInfo::cpp;
constexpr recTestInfo_language recTestInfo::c;
constexpr recTestInfo_language recTestInfo::python;
constexpr recTestInfo_language recTestInfo::language_MIN;
constexpr recTestInfo_language recTestInfo::language_MAX;
constexpr int recTestInfo::language_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class testPointResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<testPointResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(testPointResult, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x000001fe) ^ 0x000001fe) != 0;
  }
};

testPointResult::testPointResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:judge_message_for_transport.testPointResult)
}
inline PROTOBUF_NDEBUG_INLINE testPointResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::judge_message_for_transport::testPointResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        msg_(arena, from.msg_) {}

testPointResult::testPointResult(
    ::google::protobuf::Arena* arena,
    const testPointResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  testPointResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, seq_id_),
           offsetof(Impl_, result_) -
               offsetof(Impl_, seq_id_) +
               sizeof(Impl_::result_));

  // @@protoc_insertion_point(copy_constructor:judge_message_for_transport.testPointResult)
}
inline PROTOBUF_NDEBUG_INLINE testPointResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        msg_(arena) {}

inline void testPointResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_id_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, seq_id_) +
               sizeof(Impl_::result_));
}
testPointResult::~testPointResult() {
  // @@protoc_insertion_point(destructor:judge_message_for_transport.testPointResult)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void testPointResult::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    testPointResult::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_testPointResult_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            testPointResult::IsInitializedImpl,
            &testPointResult::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<testPointResult>(),
            ::google::protobuf::Message::GetNewImpl<testPointResult>(),
            ::google::protobuf::Message::GetClearImpl<testPointResult>(), &testPointResult::ByteSizeLong,
                &testPointResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(testPointResult, _impl_._cached_size_),
            false,
        },
        &testPointResult::kDescriptorMethods,
        &descriptor_table_judge_5fmessage_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* testPointResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 63, 2> testPointResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(testPointResult, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::judge_message_for_transport::testPointResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 seq_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.seq_id_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.seq_id_)}},
    // required int32 cpu_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.cpu_time_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.cpu_time_)}},
    // required int32 real_time = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.real_time_), 4>(),
     {24, 4, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.real_time_)}},
    // required int64 memory = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(testPointResult, _impl_.memory_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.memory_)}},
    // required int32 signal = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.signal_), 5>(),
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.signal_)}},
    // required int32 exit_code = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.exit_code_), 6>(),
     {48, 6, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.exit_code_)}},
    // required int32 error = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.error_), 7>(),
     {56, 7, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.error_)}},
    // required int32 result = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testPointResult, _impl_.result_), 8>(),
     {64, 8, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.result_)}},
    // optional string msg = 9;
    {::_pbi::TcParser::FastSS1,
     {74, 0, 0, PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.msg_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 seq_id = 1;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.seq_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int32 cpu_time = 2;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.cpu_time_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int32 real_time = 3;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.real_time_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int64 memory = 4;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.memory_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // required int32 signal = 5;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.signal_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int32 exit_code = 6;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.exit_code_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int32 error = 7;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.error_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required int32 result = 8;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.result_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string msg = 9;
    {PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\53\0\0\0\0\0\0\0\0\3\0\0\0\0\0\0"
    "judge_message_for_transport.testPointResult"
    "msg"
  }},
};

PROTOBUF_NOINLINE void testPointResult::Clear() {
// @@protoc_insertion_point(message_clear_start:judge_message_for_transport.testPointResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.msg_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x000000feu) {
    ::memset(&_impl_.seq_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.error_) -
        reinterpret_cast<char*>(&_impl_.seq_id_)) + sizeof(_impl_.error_));
  }
  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* testPointResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const testPointResult& this_ = static_cast<const testPointResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* testPointResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const testPointResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:judge_message_for_transport.testPointResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required int32 seq_id = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_seq_id(), target);
          }

          // required int32 cpu_time = 2;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_cpu_time(), target);
          }

          // required int32 real_time = 3;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_real_time(), target);
          }

          // required int64 memory = 4;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<4>(
                    stream, this_._internal_memory(), target);
          }

          // required int32 signal = 5;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_signal(), target);
          }

          // required int32 exit_code = 6;
          if (cached_has_bits & 0x00000040u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_exit_code(), target);
          }

          // required int32 error = 7;
          if (cached_has_bits & 0x00000080u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<7>(
                    stream, this_._internal_error(), target);
          }

          // required int32 result = 8;
          if (cached_has_bits & 0x00000100u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<8>(
                    stream, this_._internal_result(), target);
          }

          // optional string msg = 9;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "judge_message_for_transport.testPointResult.msg");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:judge_message_for_transport.testPointResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t testPointResult::ByteSizeLong(const MessageLite& base) {
          const testPointResult& this_ = static_cast<const testPointResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t testPointResult::ByteSizeLong() const {
          const testPointResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:judge_message_for_transport.testPointResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // optional string msg = 9;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
          }
          if (cached_has_bits & 0x000000feu) {
            // required int32 seq_id = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_seq_id());
            }
            // required int32 cpu_time = 2;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_cpu_time());
            }
            // required int64 memory = 4;
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_memory());
            }
            // required int32 real_time = 3;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_real_time());
            }
            // required int32 signal = 5;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_signal());
            }
            // required int32 exit_code = 6;
            if (cached_has_bits & 0x00000040u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_exit_code());
            }
            // required int32 error = 7;
            if (cached_has_bits & 0x00000080u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_error());
            }
          }
           {
            // required int32 result = 8;
            if (cached_has_bits & 0x00000100u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void testPointResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<testPointResult*>(&to_msg);
  auto& from = static_cast<const testPointResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:judge_message_for_transport.testPointResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_msg(from._internal_msg());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.seq_id_ = from._impl_.seq_id_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.cpu_time_ = from._impl_.cpu_time_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.memory_ = from._impl_.memory_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.real_time_ = from._impl_.real_time_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.signal_ = from._impl_.signal_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.exit_code_ = from._impl_.exit_code_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.error_ = from._impl_.error_;
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void testPointResult::CopyFrom(const testPointResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:judge_message_for_transport.testPointResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool testPointResult::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const testPointResult&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void testPointResult::InternalSwap(testPointResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.result_)
      + sizeof(testPointResult::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(testPointResult, _impl_.seq_id_)>(
          reinterpret_cast<char*>(&_impl_.seq_id_),
          reinterpret_cast<char*>(&other->_impl_.seq_id_));
}

::google::protobuf::Metadata testPointResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class testResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<testResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(testResult, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

testResult::testResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:judge_message_for_transport.testResult)
}
inline PROTOBUF_NDEBUG_INLINE testResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::judge_message_for_transport::testResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        results_{visibility, arena, from.results_} {}

testResult::testResult(
    ::google::protobuf::Arena* arena,
    const testResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  testResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, uuid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, uuid_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, uuid_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:judge_message_for_transport.testResult)
}
inline PROTOBUF_NDEBUG_INLINE testResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        results_{visibility, arena} {}

inline void testResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, uuid_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, uuid_) +
               sizeof(Impl_::type_));
}
testResult::~testResult() {
  // @@protoc_insertion_point(destructor:judge_message_for_transport.testResult)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void testResult::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    testResult::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_testResult_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            testResult::IsInitializedImpl,
            &testResult::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<testResult>(),
            ::google::protobuf::Message::GetNewImpl<testResult>(),
            ::google::protobuf::Message::GetClearImpl<testResult>(), &testResult::ByteSizeLong,
                &testResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(testResult, _impl_._cached_size_),
            false,
        },
        &testResult::kDescriptorMethods,
        &descriptor_table_judge_5fmessage_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* testResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> testResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(testResult, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::judge_message_for_transport::testResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 uuid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(testResult, _impl_.uuid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(testResult, _impl_.uuid_)}},
    // optional .judge_message_for_transport.testResult.errType type = 2;
    {::_pbi::TcParser::FastEr0S1,
     {16, 1, 3, PROTOBUF_FIELD_OFFSET(testResult, _impl_.type_)}},
    // repeated .judge_message_for_transport.testPointResult results = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(testResult, _impl_.results_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 uuid = 1;
    {PROTOBUF_FIELD_OFFSET(testResult, _impl_.uuid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .judge_message_for_transport.testResult.errType type = 2;
    {PROTOBUF_FIELD_OFFSET(testResult, _impl_.type_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // repeated .judge_message_for_transport.testPointResult results = 3;
    {PROTOBUF_FIELD_OFFSET(testResult, _impl_.results_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::judge_message_for_transport::testPointResult>()},
    {0, 4},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void testResult::Clear() {
// @@protoc_insertion_point(message_clear_start:judge_message_for_transport.testResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.results_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.uuid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.uuid_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* testResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const testResult& this_ = static_cast<const testResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* testResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const testResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:judge_message_for_transport.testResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required int32 uuid = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_uuid(), target);
          }

          // optional .judge_message_for_transport.testResult.errType type = 2;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_type(), target);
          }

          // repeated .judge_message_for_transport.testPointResult results = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_results_size());
               i < n; i++) {
            const auto& repfield = this_._internal_results().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:judge_message_for_transport.testResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t testResult::ByteSizeLong(const MessageLite& base) {
          const testResult& this_ = static_cast<const testResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t testResult::ByteSizeLong() const {
          const testResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:judge_message_for_transport.testResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .judge_message_for_transport.testPointResult results = 3;
             {
              total_size += 1UL * this_._internal_results_size();
              for (const auto& msg : this_._internal_results()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // required int32 uuid = 1;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_uuid());
            }
          }
           {
            // optional .judge_message_for_transport.testResult.errType type = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void testResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<testResult*>(&to_msg);
  auto& from = static_cast<const testResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:judge_message_for_transport.testResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_results()->MergeFrom(
      from._internal_results());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.uuid_ = from._impl_.uuid_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void testResult::CopyFrom(const testResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:judge_message_for_transport.testResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool testResult::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const testResult&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_results()))
    return false;
  return true;
}

void testResult::InternalSwap(testResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.results_.InternalSwap(&other->_impl_.results_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(testResult, _impl_.type_)
      + sizeof(testResult::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(testResult, _impl_.uuid_)>(
          reinterpret_cast<char*>(&_impl_.uuid_),
          reinterpret_cast<char*>(&other->_impl_.uuid_));
}

::google::protobuf::Metadata testResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class recTestInfo::_Internal {
 public:
  using HasBits =
      decltype(std::declval<recTestInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

recTestInfo::recTestInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:judge_message_for_transport.recTestInfo)
}
inline PROTOBUF_NDEBUG_INLINE recTestInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::judge_message_for_transport::recTestInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pid_(arena, from.pid_),
        code_(arena, from.code_) {}

recTestInfo::recTestInfo(
    ::google::protobuf::Arena* arena,
    const recTestInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  recTestInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.uuid_ = from._impl_.uuid_;

  // @@protoc_insertion_point(copy_constructor:judge_message_for_transport.recTestInfo)
}
inline PROTOBUF_NDEBUG_INLINE recTestInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pid_(arena),
        code_(arena) {}

inline void recTestInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.uuid_ = {};
}
recTestInfo::~recTestInfo() {
  // @@protoc_insertion_point(destructor:judge_message_for_transport.recTestInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void recTestInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pid_.Destroy();
  _impl_.code_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    recTestInfo::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_recTestInfo_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            recTestInfo::IsInitializedImpl,
            &recTestInfo::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<recTestInfo>(),
            ::google::protobuf::Message::GetNewImpl<recTestInfo>(),
            ::google::protobuf::Message::GetClearImpl<recTestInfo>(), &recTestInfo::ByteSizeLong,
                &recTestInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_._cached_size_),
            false,
        },
        &recTestInfo::kDescriptorMethods,
        &descriptor_table_judge_5fmessage_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* recTestInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 55, 2> recTestInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::judge_message_for_transport::recTestInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 uuid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(recTestInfo, _impl_.uuid_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.uuid_)}},
    // required string pid = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.pid_)}},
    // required string code = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 uuid = 1;
    {PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.uuid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required string pid = 2;
    {PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.pid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string code = 3;
    {PROTOBUF_FIELD_OFFSET(recTestInfo, _impl_.code_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\0\3\4\0\0\0\0"
    "judge_message_for_transport.recTestInfo"
    "pid"
    "code"
  }},
};

PROTOBUF_NOINLINE void recTestInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:judge_message_for_transport.recTestInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.pid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.code_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.uuid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* recTestInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const recTestInfo& this_ = static_cast<const recTestInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* recTestInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const recTestInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:judge_message_for_transport.recTestInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required int32 uuid = 1;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_uuid(), target);
          }

          // required string pid = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_pid();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "judge_message_for_transport.recTestInfo.pid");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // required string code = 3;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_code();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "judge_message_for_transport.recTestInfo.code");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:judge_message_for_transport.recTestInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t recTestInfo::ByteSizeLong(const MessageLite& base) {
          const recTestInfo& this_ = static_cast<const recTestInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t recTestInfo::ByteSizeLong() const {
          const recTestInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:judge_message_for_transport.recTestInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // required string pid = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_pid());
            }
            // required string code = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_code());
            }
            // required int32 uuid = 1;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_uuid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void recTestInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<recTestInfo*>(&to_msg);
  auto& from = static_cast<const recTestInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:judge_message_for_transport.recTestInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pid(from._internal_pid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_code(from._internal_code());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.uuid_ = from._impl_.uuid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void recTestInfo::CopyFrom(const recTestInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:judge_message_for_transport.recTestInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool recTestInfo::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const recTestInfo&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void recTestInfo::InternalSwap(recTestInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pid_, &other->_impl_.pid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_, &other->_impl_.code_, arena);
        swap(_impl_.uuid_, other->_impl_.uuid_);
}

::google::protobuf::Metadata recTestInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace judge_message_for_transport
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_judge_5fmessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
